<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-79OMTUBQ" ignored="2" name="Default test(failed)(failed)" tests="4" failures="1" timestamp="30 Apr 2022 08:45:39 GMT" time="0.156" errors="0">
  <testcase name="test2" time="0.031" classname="org.test.B">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="org.test.B">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="org.test.B">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.0" classname="org.test.B">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.test.B.test2(B.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="org.test.B">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.0" classname="org.test.B">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed)(failed) -->
